{\rtf1\ansi\ansicpg1252\cocoartf1348\cocoasubrtf170
{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;}
\margl1440\margr1440\vieww10380\viewh7200\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural

\f0\fs22 \cf0 \CocoaLigature0 Reduced test has 9 steps\
REDUCED IN 0.0312039852142 SECONDS\
STEP 0 INT1=9 \
STEP 1 INT0=18 \
STEP 2 INT3=12 \
STEP 3 TREE0=red.RedBlackTree( ) \
STEP 4 TREE0.add(INT1) ; print TREE0 \
STEP 5 TREE0.add(INT0) ; print TREE0 \
STEP 6 TREE0.add(INT0) ; print TREE0 \
STEP 7 TREE0.add(INT3) ; print TREE0 \
STEP 8 TREE0.add(INT0) ; print TREE0 \
\
FINAL VERSION OF TEST, WITH LOGGED REPLAY:\
INT1=9    # STEP 0\
INT0=18    # STEP 1\
INT3=12    # STEP 2\
TREE0=red.RedBlackTree( )    # STEP 3\
TREE0.add(INT1) ; print TREE0    # STEP 4\
(root.size = 1 root is )9\
TREE0.add(INT0) ; print TREE0    # STEP 5\
(root.size = 2 root is )9\
   18\
TREE0.add(INT0) ; print TREE0    # STEP 6\
(root.size = 3 root is )18\
   9\
   18\
TREE0.add(INT3) ; print TREE0    # STEP 7\
(root.size = 4 root is )18\
   9\
      12\
   18\
TREE0.add(INT0) ; print TREE0    # STEP 8\
(root.size = 5 root is )18\
   9\
      12\
   18\
      18\
ERROR: (<type 'exceptions.AssertionError'>, AssertionError(), <traceback object at 0x108750368>)\
TRACEBACK:\
  File "/Users/shinsuguruhan/tstl/generators/sut.py", line 1996, in check\
    assert self.p_TREE[0].size < 5\
STOPPING TESTING DUE TO FAILED TEST\
Traceback (most recent call last):\
  File "randomtester.py", line 410, in <module>\
    print t.report(config.coverfile),"PERCENT COVERED"\
AttributeError: 'sut' object has no attribute 'report'\
10-248-57-56:generators shinsuguruhan$ \
}